const C=window.TURNARIO_CONFIG||{};
const app=document.getElementById("app");
const state={screen:"access",pin:"",setup:localStorage.getItem("tvvf_admin_pin")==null,section:"dashboard",people:[],loading:false,peopleLoaded:false,vvfPeople:[],vvfSelected:null,vvfToken:localStorage.getItem("tvvf_session")||"",me:null,vvfTypes:[],vvfRequests:[],pendingRequests:[],vvfSharedAbsences:[],isValidator:false,isCoffeeManager:false};

function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
async function sbRpc(fn,body={}){
  if(!C.supabaseUrl||!C.supabasePublishableKey) throw new Error("Configurazione Supabase mancante");
  const adminPin=localStorage.getItem("tvvf_admin_pin");
  if(fn.startsWith("vvf_admin_") && adminPin) body={...body,p_admin_pin:adminPin};
  const r=await fetch(`${C.supabaseUrl}/rest/v1/rpc/${fn}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":C.supabasePublishableKey,"Authorization":`Bearer ${C.supabasePublishableKey}`},body:JSON.stringify(body)});
  const text=await r.text();
  let data; try{data=text?JSON.parse(text):null}catch{data=text}
  if(!r.ok) throw new Error(data?.message||data?.hint||data?.details||data?.error||"Errore Supabase");
  return data;
}
async function sbRest(path,options={}){
  if(!C.supabaseUrl||!C.supabasePublishableKey) throw new Error("Configurazione Supabase mancante");
  const r=await fetch(`${C.supabaseUrl}/rest/v1/${path}`,{headers:{"apikey":C.supabasePublishableKey,"Authorization":`Bearer ${C.supabasePublishableKey}`,...(options.headers||{})},...options});
  const text=await r.text(); let data; try{data=text?JSON.parse(text):null}catch{data=text}
  if(!r.ok) throw new Error(data?.message||data?.hint||data?.details||data?.error||"Errore Supabase");
  return data;
}
function vvfSession(){return state.vvfToken||localStorage.getItem("tvvf_session")||""}
function vvfLogout(){state.vvfToken="";state.me=null;state.vvfRequests=[];state.pendingRequests=[];state.vvfSharedAbsences=[];state.isValidator=false;state.isCoffeeManager=false;localStorage.removeItem("tvvf_session");localStorage.removeItem("tvvf_me");state.screen="access";state.pin="";render()}

function layout(content){return `<div class="shell"><header class="topbar"><div class="brand"><div class="brand-mark">🔥</div><div>Turnario VVF<small>Gestione distaccamento</small></div></div><span class="badge" style="background:#fff;color:#9b111e">AMMINISTRATORE</span></header>${content}<nav class="mobile-nav"><button onclick="go('dashboard')">🏠<br>Dashboard</button><button onclick="go('personale')">👨‍🚒<br>Personale</button><button onclick="go('parametri')">⚙️<br>Parametri</button><button onclick="go('richieste')">📋<br>Richieste</button><button onclick="go('caffe')">☕<br>Caffè</button></nav></div>`}
function vvfLayout(content){const me=state.me||{};return `<div class="shell"><header class="topbar"><div class="brand"><div class="brand-mark">🔥</div><div>Turnario VVF<small>${esc(me.nome||'Area personale')} ${esc(me.cognome||'')}</small></div></div><span class="badge">${esc(me.ruolo||'VVF')}</span></header>${content}<nav class="mobile-nav"><button onclick="vvfGo('home')">🏠<br>Home</button><button onclick="vvfGo('turnario')">📅<br>Turnario</button><button onclick="vvfGo('richieste')">📋<br>Richieste</button>${state.isCoffeeManager?`<button onclick="vvfGo('caffe')">☕<br>Caffè</button>`:''}<button onclick="vvfLogout()">🚪<br>Esci</button></nav></div>`}
function pinScreen(){const title=state.setup?"Configura amministratore":"Accesso amministratore";const sub=state.setup?"Imposta il PIN di 4 cifre per il primo accesso.":"Inserisci il PIN amministratore.";return `<main class="login"><section class="card login-card"><div class="eyebrow">Turnario VVF</div><h1 class="title">${title}</h1><p class="muted">${sub}</p><div class="pin-dots">${[0,1,2,3].map(i=>`<i class="dot ${state.pin.length>i?"on":""}"></i>`).join("")}</div><div class="pin-grid">${[1,2,3,4,5,6,7,8,9].map(n=>`<button class="pin-key" onclick="key('${n}')">${n}</button>`).join("")}<button class="pin-key" onclick="key('clear')">⌫</button><button class="pin-key" onclick="key('0')">0</button><button class="pin-key" onclick="key('ok')">✓</button></div><button class="btn btn-soft" style="margin-top:14px;width:100%" onclick="showAccess()">← Torna agli accessi</button><div class="notice">PIN amministratore separato dal PIN personale dei VVF.</div></section></main>`}
function accessScreen(){return `<main class="login"><section class="card login-card"><div class="eyebrow">Turnario VVF</div><h1 class="title">Accesso</h1><p class="muted">Scegli come entrare nel sistema.</p><div class="grid" style="gap:12px"><button class="btn btn-primary" onclick="adminAccess()">🔐 Amministratore</button><button class="btn btn-soft" onclick="vvfAccess()">👨‍🚒 Accesso VVF</button></div><div class="notice" style="margin-top:14px">Ogni VVF usa il proprio PIN. I Capi Squadra possono essere abilitati alla validazione; il Gestore Caffè è un permesso indipendente dal grado.</div></section></main>`}
function vvfAccessScreen(){if(!state.vvfPeople.length)return `<main class="login"><section class="card login-card"><div class="eyebrow">Turnario VVF</div><h1 class="title">Accesso VVF</h1><p class="muted">Caricamento personale…</p></section></main>`;return `<main class="login"><section class="card login-card"><div class="eyebrow">Turnario VVF</div><h1 class="title">Scegli il tuo profilo</h1><div class="list">${state.vvfPeople.map(p=>`<button class="row" style="width:100%;text-align:left;border:1px solid #e4e6ea;background:#fff;cursor:pointer" onclick="selectVvf('${p.id}')"><div class="row-left"><div class="avatar">${esc((p.nome||'?')[0])}${esc((p.cognome||'?')[0])}</div><div><b>${esc(p.nome)} ${esc(p.cognome)}</b><div class="muted">${esc(p.ruolo)} · turno ${esc(p.turno||'—')} · salto ${p.salto??'—'}</div></div></div><span class="badge">›</span></button>`).join('')}</div><button class="btn btn-soft" style="margin-top:14px;width:100%" onclick="showAccess()">← Indietro</button></section></main>`}
function vvfPinScreen(){const p=state.vvfSelected||{};return `<main class="login"><section class="card login-card"><div class="eyebrow">Accesso VVF</div><h1 class="title">${esc(p.nome)} ${esc(p.cognome)}</h1><p class="muted">Inserisci il tuo PIN di 4 cifre.</p><div class="pin-dots">${[0,1,2,3].map(i=>`<i class="dot ${state.pin.length>i?"on":""}"></i>`).join("")}</div><div class="pin-grid">${[1,2,3,4,5,6,7,8,9].map(n=>`<button class="pin-key" onclick="vvfKey('${n}')">${n}</button>`).join('')}<button class="pin-key" onclick="vvfKey('clear')">⌫</button><button class="pin-key" onclick="vvfKey('0')">0</button><button class="pin-key" onclick="vvfKey('ok')">✓</button></div><button class="btn btn-soft" style="margin-top:14px;width:100%" onclick="vvfAccess()">← Cambia profilo</button></section></main>`}
function showAccess(){state.screen="access";state.pin="";render()}
async function vvfAccess(){state.screen="vvfList";state.vvfPeople=[];render();try{state.vvfPeople=await sbRpc('vvf_list_login_personale',{});if(!Array.isArray(state.vvfPeople))state.vvfPeople=[];render()}catch(e){alert(e.message);showAccess()}}
function selectVvf(id){state.vvfSelected=state.vvfPeople.find(p=>p.id===id)||null;state.pin="";state.screen="vvfPin";render()}
function vvfKey(k){if(k==='clear')state.pin=state.pin.slice(0,-1);else if(k==='ok'){if(state.pin.length!==4)return;loginVvf()}else if(state.pin.length<4)state.pin+=k;render()}
async function loginVvf(){try{const data=await sbRpc('vvf_login',{p_persona_id:state.vvfSelected.id,p_pin:state.pin});state.vvfToken=data.token;state.me={...data,turno:data.turno||state.vvfSelected?.turno||'',salto:data.salto??state.vvfSelected?.salto??null};localStorage.setItem('tvvf_session',data.token);localStorage.setItem('tvvf_me',JSON.stringify(data));state.pin='';state.screen='vvf';state.section='home';await loadVvfPermissions();await loadVvfRequests();render()}catch(e){alert(e.message);state.pin='';render()}}
async function loadVvfPermissions(){try{state.isValidator=!!(await sbRpc('vvf_is_validatore_assenze',{p_session_token:vvfSession()}));}catch{state.isValidator=state.me?.ruolo==='CAPO_SQUADRA'}try{state.isCoffeeManager=!!(await sbRpc('vvf_is_gestore_caffe',{p_session_token:vvfSession()}));}catch{state.isCoffeeManager=false}}
async function loadVvfRequests(){try{state.vvfRequests=await sbRpc('vvf_mie_richieste',{p_session_token:vvfSession()});if(!Array.isArray(state.vvfRequests))state.vvfRequests=[]}catch(e){if(vvfSession())localStorage.removeItem('tvvf_session');state.vvfRequests=[]}}
function vvfHome(){const me=state.me||{};return vvfLayout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Area personale</div><h1 class="title">Ciao ${esc(me.nome||'') }</h1><div class="muted">Turno ${esc(me.turno||'—')} · salto ${me.salto??'—'} · ${esc(me.ruolo||'VVF')}</div></div><button class="btn btn-soft" onclick="vvfLogout()">Esci</button></div><div class="grid grid2 section"><button class="card tile" onclick="vvfGo('turnario')"><div style="font-size:28px">📅</div><h3>Turnario</h3><p>Consulta il calendario completo e le ferie approvate dei colleghi.</p></button><button class="card tile" onclick="vvfGo('richieste')"><div style="font-size:28px">📋</div><h3>Le mie richieste</h3><p>${state.vvfRequests.length} richieste registrate.</p></button>${state.isValidator?`<button class="card tile" onclick="vvfGo('valida')"><div style="font-size:28px">✅</div><h3>Validazione ferie</h3><p>Richieste in attesa del tuo distaccamento.</p></button>`:''}${state.isCoffeeManager?`<button class="card tile" onclick="vvfGo('caffe')"><div style="font-size:28px">☕</div><h3>Gestione Caffè</h3><p>Accesso indipendente dal grado.</p></button>`:''}</div></main>`)}
function vvfRequestsPage(){return vvfLayout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Area personale</div><h1 class="title">Le mie richieste</h1></div><button class="btn btn-primary" onclick="showVvfRequestForm()">+ Nuova richiesta</button></div><section class="card" style="padding:20px"><div id="vvf-request-form"></div><div class="list">${state.vvfRequests.length?state.vvfRequests.map(r=>`<div class="row"><div><b>${esc(r.tipo_nome)}</b><div class="muted">${esc(r.data_inizio)} → ${esc(r.data_fine)}</div><div class="muted">${esc(r.stato)}${r.motivo_esito?` · ${esc(r.motivo_esito)}`:''}</div></div><span class="badge ${r.stato==='APPROVATA'?'':'red'}">${esc(r.stato)}</span></div>`).join(''):'<div class="notice">Nessuna richiesta registrata.</div>'}</div></section></main>`)}
function showVvfRequestForm(presetDate=null){const el=document.getElementById('vvf-request-form');if(!el)return;el.innerHTML=`<div class="form-panel"><div class="section-head"><h3>Nuova richiesta ferie/assenza</h3><button class="btn btn-soft" onclick="this.closest('.form-panel').remove()">Chiudi</button></div><div class="grid grid2"><div class="field"><label class="label">Tipo assenza</label><select id="vr-tipo" class="input"><option value="">Caricamento…</option></select></div><div class="field"><label class="label">Data inizio</label><input id="vr-inizio" class="input" type="date" value="${presetDate||''}"></div><div class="field"><label class="label">Note</label><textarea id="vr-note" class="input" rows="3" placeholder="Note facoltative"></textarea></div></div><button class="btn btn-primary" onclick="sendVvfRequest()">Invia richiesta</button><div id="vr-msg"></div></div>`;loadVvfTypes()}
async function loadVvfTypes(){try{state.vvfTypes=await sbRest('vvf_tipi_assenza?select=id,codice,nome,limite_contemporaneo,richiede_approvazione,visibile_a_tutti&attivo=eq.true&order=nome.asc');const s=document.getElementById('vr-tipo');if(s)s.innerHTML=state.vvfTypes.length?state.vvfTypes.map(t=>`<option value="${t.id}">${esc(t.nome)}</option>`).join(''):'<option value="">Nessun tipo attivo</option>'}catch(e){const s=document.getElementById('vr-tipo');if(s)s.innerHTML='<option value="">Impossibile caricare i tipi</option>';const m=document.getElementById('vr-msg');if(m)m.innerHTML=`<div class="notice">${esc(e.message)}. Se i tipi non sono esposti via REST, collegheremo una funzione RPC dedicata.</div>`}}
async function sendVvfRequest(){const tipo=document.getElementById('vr-tipo')?.value,inizio=document.getElementById('vr-inizio')?.value,fine=inizio,note=document.getElementById('vr-note')?.value||null,msg=document.getElementById('vr-msg');if(!tipo||!inizio||!fine){msg.innerHTML='<div class="notice">Tipo e date sono obbligatori.</div>';return}try{msg.innerHTML='<div class="notice">Invio…</div>';const r=await sbRpc('vvf_invia_richiesta',{p_session_token:vvfSession(),p_tipo_id:tipo,p_data_inizio:inizio,p_data_fine:fine,p_note:note});msg.innerHTML=`<div class="notice">Richiesta registrata: <b>${esc(r.stato)}</b>.</div>`;await loadVvfRequests();setTimeout(render,500)}catch(e){msg.innerHTML=`<div class="notice">Errore: ${esc(e.message)}</div>`}}
function vvfValidationPage(){if(!state.isValidator)return vvfHome();if(!state.pendingRequests.length)loadVvfPending();return vvfLayout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Capo Squadra</div><h1 class="title">Validazione richieste</h1></div><button class="btn btn-soft" onclick="vvfGo('home')">← Home</button></div><section class="card" style="padding:20px"><div id="pending-wrap">${state.pendingRequests.length?state.pendingRequests.map(r=>`<div class="row"><div><b>${esc(r.persona_nome)} ${esc(r.persona_cognome)}</b><div>${esc(r.tipo_nome)}</div><div class="muted">${esc(r.data_inizio)} → ${esc(r.data_fine)}</div></div><div class="actions"><button class="btn btn-primary btn-small" onclick="decideVvfRequest('${r.id}',true)">Approva</button><button class="btn btn-danger btn-small" onclick="decideVvfRequest('${r.id}',false)">Rifiuta</button></div></div>`).join(''):'<div class="notice">Nessuna richiesta in attesa.</div>'}</div></section></main>`)}
async function loadVvfPending(){try{state.pendingRequests=await sbRpc('vvf_richieste_da_validare',{p_session_token:vvfSession()});if(!Array.isArray(state.pendingRequests))state.pendingRequests=[];render()}catch(e){alert(e.message)}}
async function decideVvfRequest(id,approve){let motivo=null;if(!approve){motivo=prompt('Motivo del rifiuto:')||'Rifiutata dal validatore'}try{await sbRpc('vvf_decidi_richiesta',{p_session_token:vvfSession(),p_richiesta_id:id,p_approva:approve,p_motivo:motivo});await loadVvfPending();await loadVvfRequests()}catch(e){alert(e.message)}}
function vvfPeopleForCode(code){if(!code)return [];return state.vvfPeople.filter(p=>p.turno===code.letter&&Number(p.salto)===Number(code.cycle))}
function vvfAbsencesForDay(ds){return (state.vvfSharedAbsences||[]).filter(r=>r.data_inizio<=ds&&r.data_fine>=ds)}
function vvfSharedTurnario(){
  const me=state.me||{};
  const team=me.turno||'A';
  const salto=Number(me.salto||0);
  const saved=window.__vvfTurnView||{year:new Date().getFullYear(),month:new Date().getMonth(),team};
  saved.team=team;
  window.__vvfTurnView=saved;
  const monthNames=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
  const cells=monthGridDays(saved.year,saved.month), today=new Date(), todayIso=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
  const teamPeople=state.vvfPeople.filter(p=>p.turno===team).sort((a,b)=>Number(a.salto||99)-Number(b.salto||99)||a.cognome.localeCompare(b.cognome));
  const cellHtml=cells.map(day=>{
    if(!day)return '<div class="turn-cell empty"></div>';
    const ds=`${saved.year}-${String(saved.month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
    const info=realCycleInfo(ds,team);
    const mioTurno=!!(info.code && Number(info.code.cycle)===salto);
    let service='';
    if(info.phase==='Diurno') service=`<div class="turn-shift day"><b>${info.label}</b><br>DIURNO</div>`;
    else if(info.phase==='Notturno') service=`<div class="turn-shift night"><b>${info.label}</b><br>NOTTURNO</div>`;
    else if(info.phase==='Smontante') service='<div class="turn-shift rest">SMONTANTE</div>';
    else service='<div class="turn-shift rest">RIPOSO</div>';
    const abs=vvfAbsencesForDay(ds);
    const absHtml=abs.length?`<div class="turn-absence">${abs.slice(0,2).map(r=>`FERIE: ${esc(r.nome)} ${esc(r.cognome)}`).join('<br>')}${abs.length>2?`<br>+${abs.length-2} assenze`:''}</div>`:'';
    const mioBadge=mioTurno?'<div class="turn-names"><b>IL MIO TURNO</b></div>':'';
    return `<button class="turn-cell ${ds===todayIso?'today ':''}${mioTurno?'my-turn':''}" onclick="vvfSelectTurnDate('${ds}')"><span class="turn-day-number">${day}</span>${service}${mioBadge}${absHtml}</button>`;
  }).join('');
  const roster=teamPeople.length?teamPeople.map(p=>`<div class="turn-person ${Number(p.salto)===salto?'my-person':''}"><span><b>${esc(p.nome)} ${esc(p.cognome)}</b><small>${esc(p.ruolo||'VIGILE')} · Turno ${esc(p.turno)} · Salto ${p.salto??'—'}</small></span><span class="badge">${esc(p.turno)}${p.salto||'—'}</span></div>`).join(''):'<div class="notice">Nessun VVF attivo assegnato al tuo turno.</div>';
  return vvfLayout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Calendario personale e condiviso</div><h1 class="title">Turnario</h1><div class="muted">Il tuo turno è impostato dall'amministratore e non può essere modificato da qui.</div></div><button class="btn btn-soft" onclick="vvfGo('home')">← Home</button></div>
    <section class="card" style="padding:20px">
      <div class="turn-toolbar"><button class="btn btn-soft" onclick="vvfTurnMonth(-1)">‹</button><div class="turn-month-title">${monthNames[saved.month]} ${saved.year}</div><button class="btn btn-soft" onclick="vvfTurnMonth(1)">›</button></div>
      <div class="notice"><b>Il tuo turno:</b> ${esc(team)} · <b>Salto:</b> ${salto||'—'} · <b>Profilo:</b> ${esc(me.nome||'')} ${esc(me.cognome||'')}<br><span class="muted">Il calendario mostra il turno assegnato dall'amministratore. Le giornate del tuo salto sono evidenziate. <b>Premi su una giornata per richiedere ferie/assenza.</b></span></div>
      <div class="turn-calendar-wrap"><div class="turn-weekdays">${['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=>`<div>${x}</div>`).join('')}</div><div class="turn-calendar">${cellHtml}</div></div>
      <div id="vvf-turn-date-detail"></div>
      <div class="section"><h3>Personale del turno ${esc(team)}</h3>${roster}</div>
      <div class="section"><h3>Ferie/assenze approvate</h3><div id="vvf-shared-absences">${state.vvfSharedAbsences.length?state.vvfSharedAbsences.map(r=>`<div class="row"><div><b>${esc(r.nome)} ${esc(r.cognome)}</b><div>${esc(r.tipo_nome)}</div><div class="muted">${esc(r.data_inizio)} → ${esc(r.data_fine)}</div></div><span class="badge">APPROVATA</span></div>`).join(''):'<div class="notice">Nessuna assenza approvata nel mese visualizzato.</div>'}</div></div>
    </section></main>`);
}
function vvfTurnMonth(delta){const v=window.__vvfTurnView||{year:new Date().getFullYear(),month:new Date().getMonth(),team:state.me?.turno||'A'};v.team=state.me?.turno||v.team||'A';v.month+=delta;if(v.month<0){v.month=11;v.year--}if(v.month>11){v.month=0;v.year++}window.__vvfTurnView=v;state.vvfSharedAbsences=[];render();loadSharedAbsencesForVvfMonth()}
function vvfSetTurnTeam(team){window.__vvfTurnView={...(window.__vvfTurnView||{}),team};render();}
function vvfSelectTurnDate(ds){const v=window.__vvfTurnView||{team:state.me?.turno||'A'},info=realCycleInfo(ds,v.team),abs=vvfAbsencesForDay(ds),el=document.getElementById('vvf-turn-date-detail');if(!el)return;const d=new Date(ds+'T12:00:00').toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const myWork=!!(info.code&&Number(info.code.cycle)===Number(state.me?.salto));if(!myWork){el.innerHTML=`<section class="card turn-detail"><div class="section-head"><div><div class="eyebrow">${d}</div><h3>${info.label?`${info.label} · ${info.phase}`:info.phase}</h3></div><button class="btn btn-soft btn-small" onclick="this.closest('.turn-detail').remove()">Chiudi</button></div>${abs.length?`<div class="section"><h4>Assenze approvate</h4>${abs.map(r=>`<div class="row"><div><b>${esc(r.nome)} ${esc(r.cognome)}</b><div>${esc(r.tipo_nome)}</div></div><span class="badge">APPROVATA</span></div>`).join('')}</div>`:''}<div class="notice">Questa non è una giornata lavorativa del tuo salto. Le ferie si possono richiedere solo sulle tue giornate lavorative.</div></section>`;el.scrollIntoView({behavior:'smooth',block:'nearest'});return}if(!confirm(`Vuoi inserire una richiesta di ferie/assenza per ${d}?`))return;el.innerHTML=`<section class="card turn-detail"><div class="section-head"><div><div class="eyebrow">${d}</div><h3>${info.label} · ${info.phase}</h3></div><button class="btn btn-soft btn-small" onclick="this.closest('.turn-detail').remove()">Chiudi</button></div>${abs.length?`<div class="section"><h4>Assenze approvate</h4>${abs.map(r=>`<div class="row"><div><b>${esc(r.nome)} ${esc(r.cognome)}</b><div>${esc(r.tipo_nome)}</div></div><span class="badge">APPROVATA</span></div>`).join('')}</div>`:''}<div id="vvf-request-form"></div></section>`;showVvfRequestForm(ds);const fine=document.getElementById('vr-fine');if(fine)fine.closest('.field')?.remove();el.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function loadSharedAbsencesForVvfMonth(){const v=window.__vvfTurnView||{year:new Date().getFullYear(),month:new Date().getMonth()};const start=`${v.year}-${String(v.month+1).padStart(2,'0')}-01`,end=`${v.year}-${String(v.month+1).padStart(2,'0')}-${String(new Date(v.year,v.month+1,0).getDate()).padStart(2,'0')}`;try{const rows=await sbRpc('vvf_assenze_condivise',{p_session_token:vvfSession(),p_data_inizio:start,p_data_fine:end});state.vvfSharedAbsences=Array.isArray(rows)?rows:[];render()}catch(e){state.vvfSharedAbsences=[];render()}}
async function loadSharedAbsences(){return loadSharedAbsencesForVvfMonth()}
async function loadSharedAbsences(){const el=document.getElementById('vvf-shared-absences');if(!el)return;try{const today=new Date(),start=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-01`,end=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(new Date(today.getFullYear(),today.getMonth()+1,0).getDate()).padStart(2,'0')}`;const rows=await sbRpc('vvf_assenze_condivise',{p_session_token:vvfSession(),p_data_inizio:start,p_data_fine:end});el.innerHTML=rows.length?rows.map(r=>`<div class="row"><div><b>${esc(r.nome)} ${esc(r.cognome)}</b><div>${esc(r.tipo_nome)}</div><div class="muted">${esc(r.data_inizio)} → ${esc(r.data_fine)}</div></div><span class="badge">${esc(r.stato)}</span></div>`).join(''):'<div class="notice">Nessuna assenza approvata nel mese corrente.</div>'}catch(e){el.innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
function vvfCoffeePage(){if(!state.isCoffeeManager)return vvfHome();return vvfLayout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Permesso delegato</div><h1 class="title">Gestione Caffè</h1></div><button class="btn btn-soft" onclick="vvfGo('home')">← Home</button></div><section class="card" style="padding:20px"><div class="notice">Gestore Caffè abilitato. Il modulo contabilità/QR verrà collegato alle funzioni del progetto Caffè senza dipendere dal ruolo VVF.</div></section></main>`)}
function vvfGo(s){state.section=s;render();if(s==='valida'&&state.isValidator&&!state.pendingRequests.length)loadVvfPending();if(s==='richieste'&&state.vvfToken&&!state.vvfRequests.length)loadVvfRequests();if(s==='turnario'&&state.vvfToken)loadSharedAbsencesForVvfMonth()}

function dashboard(){const n=state.people.length?state.people.filter(p=>p.attivo).length:"—";return layout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Panoramica</div><h1 class="title">Dashboard amministratore</h1><div class="muted">Distaccamento configurabile e personale sostituibile senza perdere lo storico.</div></div><button class="btn btn-soft" onclick="logout()">Esci</button></div><div class="grid grid4 section">${stat("👨‍🚒","Personale",n,"attivi da Supabase")} ${stat("🟢","Presenze","—","da collegare al turnario")} ${stat("📋","Richieste","0","da approvare")} ${stat("☕","Caffè","0","periodo corrente")}</div><div class="grid grid2 section">${tile("👨‍🚒","Personale","Inserisci, modifica o disattiva i VVF direttamente nel database.","personale")}${tile("⚙️","Parametri","Numeri minimi, CS, autisti, turni e salti.","parametri")}${tile("📅","Turnario","Vista del calendario A/B/C/D e assegnazioni.","turnario")}${tile("📋","Richieste","Ferie, licenze, 104, malattia e congedi.","richieste")}${tile("☕","Caffè","QR unico, quantità, conteggi, pagamenti e azzeramento.","caffe")}${tile("💾","Storico e backup","Operazioni, richieste e movimenti conservati nello storico.","storico")}</div></main>`)}
function stat(icon,t,n,s){return `<div class="card stat"><div>${icon}</div><div class="n">${esc(n)}</div><div>${t}</div><div class="muted">${s}</div></div>`}
function tile(icon,t,p,target){return `<button class="card tile" style="text-align:left;border:1px solid #e4e6ea;background:#fff;cursor:pointer" onclick="go('${target}')"><div style="font-size:25px">${icon}</div><h3>${t}</h3><p>${p}</p></button>`}
function page(title,desc,body){return layout(`<main class="container"><div class="section-head"><div><div class="eyebrow">Amministrazione</div><h1 class="title">${title}</h1><div class="muted">${desc}</div></div><button class="btn btn-soft" onclick="go('dashboard')">← Dashboard</button></div><section class="card" style="padding:20px">${body}</section></main>`)}
function personnel(){if(state.loading)return page("Personale","Gestione nominativi e ruoli del distaccamento.",`<div class="notice">Caricamento personale da Supabase…</div>`);const rows=state.people.length?state.people.map((p,i)=>`<div class="row"><div class="row-left"><div class="avatar">${i+1}</div><div><b>${esc(p.nome)} ${esc(p.cognome)}</b><div class="muted">${esc(p.ruolo||"VIGILE")} · turno ${esc(p.turno||"—")} · salto ${p.salto??"—"}</div></div></div><div class="actions"><span class="badge ${p.attivo?"":"red"}">${p.attivo?"ATTIVO":"DISATTIVO"}</span><button class="btn btn-soft btn-small" onclick="editPerson('${p.id}')">Modifica</button>${p.attivo?`<button class="btn btn-danger btn-small" onclick="disablePerson('${p.id}')">Disattiva</button>`:""}</div></div>`).join(""): `<div class="notice">Nessun dipendente presente in Supabase. Puoi aggiungerlo qui.</div>`;const cs=state.people.filter(p=>p.ruolo==="CAPO_SQUADRA").length,au=state.people.filter(p=>p.ruolo==="AUTISTA").length,vi=state.people.filter(p=>p.ruolo==="VIGILE").length;return page("Personale","Gestione nominativi e ruoli del distaccamento.",`<div class="section-head"><div><b>${state.people.length} profili</b><div class="muted">${cs} Capi Squadra · ${au} Autisti · ${vi} Vigili</div></div><button class="btn btn-primary" onclick="showPersonForm()">+ Aggiungi VVF</button></div><div class="list">${rows}</div><div id="person-form"></div>`)}
function personForm(p=null){const edit=!!p;return `<div class="form-panel"><div class="section-head"><h3>${edit?"Modifica VVF":"Nuovo VVF"}</h3><button class="btn btn-soft" onclick="document.getElementById('person-form').innerHTML=''">Chiudi</button></div><div class="grid grid2"><div class="field"><label class="label">Nome</label><input id="pf-nome" class="input" value="${esc(p?.nome||"")}" autocomplete="off"></div><div class="field"><label class="label">Cognome</label><input id="pf-cognome" class="input" value="${esc(p?.cognome||"")}" autocomplete="off"></div><div class="field"><label class="label">Ruolo</label><select id="pf-ruolo" class="input">${["VIGILE","AUTISTA","CAPO_SQUADRA"].map(x=>`<option ${p?.ruolo===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label class="label">Turno</label><select id="pf-turno" class="input">${["A","B","C","D"].map(x=>`<option ${p?.turno===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label class="label">Salto</label><select id="pf-salto" class="input"><option value="">Seleziona</option>${[1,2,3,4,5,6,7,8].map(x=>`<option value="${x}" ${Number(p?.salto)===x?"selected":""}>${x}</option>`).join("")}</select><div class="muted">Ogni turno ha 8 salti: A1–A8, B1–B8, C1–C8, D1–D8.</div></div><div class="field"><label class="label">PIN VVF ${edit?"(lascia vuoto per non cambiarlo)":""}</label><input id="pf-pin" class="input" type="password" inputmode="numeric" maxlength="4" placeholder="4 cifre" autocomplete="new-password"></div><div class="field check-field"><label><input id="pf-attivo" type="checkbox" ${p?.attivo!==false?"checked":""}> Profilo attivo</label></div></div><button class="btn btn-primary" onclick="savePerson(${edit?`'${p.id}'`:"null"})">${edit?"Salva modifiche":"Crea VVF"}</button><div id="pf-msg"></div></div>`}
async function loadPeople(){if(state.loading)return;state.loading=true;render();try{state.people=await sbRpc("vvf_admin_list_personale",{});if(!Array.isArray(state.people))state.people=[];state.peopleLoaded=true;}catch(e){alert(e.message)}finally{state.loading=false;render()}}
function showPersonForm(){const el=document.getElementById("person-form");if(el)el.innerHTML=personForm()}
function editPerson(id){const p=state.people.find(x=>x.id===id);const el=document.getElementById("person-form");if(el&&p){el.innerHTML=personForm(p);el.scrollIntoView({behavior:"smooth",block:"center"})}}
async function savePerson(id){const nome=document.getElementById("pf-nome").value.trim(),cognome=document.getElementById("pf-cognome").value.trim(),ruolo=document.getElementById("pf-ruolo").value,turno=document.getElementById("pf-turno").value,salto=document.getElementById("pf-salto").value?Number(document.getElementById("pf-salto").value):null,pin=document.getElementById("pf-pin").value.trim(),attivo=document.getElementById("pf-attivo").checked;const msg=document.getElementById("pf-msg");if(!nome||!cognome){msg.innerHTML='<div class="notice">Nome e cognome sono obbligatori.</div>';return}if(pin&&!/^\d{4}$/.test(pin)){msg.innerHTML='<div class="notice">Il PIN deve essere di 4 cifre.</div>';return}try{msg.innerHTML='<div class="notice">Salvataggio…</div>';if(id){await sbRpc("vvf_admin_update_personale",{p_id:id,p_nome:nome,p_cognome:cognome,p_ruolo:ruolo,p_turno:turno,p_pin:pin||null,p_attivo:attivo,p_salto:salto})}else{await sbRpc("vvf_admin_add_personale",{p_nome:nome,p_cognome:cognome,p_ruolo:ruolo,p_turno:turno,p_pin:pin||null,p_attivo:attivo,p_salto:salto})}await loadPeople()}catch(e){msg.innerHTML=`<div class="notice">Errore: ${esc(e.message)}</div>`}}
async function disablePerson(id){if(!confirm("Disattivare questo profilo? Lo storico non verrà cancellato."))return;try{await sbRpc("vvf_admin_update_personale",{p_id:id,p_nome:null,p_cognome:null,p_ruolo:null,p_turno:null,p_pin:null,p_attivo:false});await loadPeople()}catch(e){alert(e.message)}}
function params(){return page("Parametri","Configurazione adattabile a qualsiasi distaccamento.",`<div class="grid grid2"><div class="field"><label class="label">Nome distaccamento</label><input class="input" value="Desio"></div><div class="field"><label class="label">Turno</label><select class="input"><option>A</option><option>B</option><option selected>C</option><option>D</option></select></div><div class="field"><label class="label">Minimo totale</label><input class="input" type="number" value="1"></div><div class="field"><label class="label">Minimo Capi Squadra</label><input class="input" type="number" value="1"></div><div class="field"><label class="label">Minimo autisti</label><input class="input" type="number" value="1"></div><div class="field"><label class="label">Limite assenze</label><input class="input" type="number" value="3"></div></div><button class="btn btn-primary" onclick="alert('Parametri salvati nel collaudo locale')">Salva parametri</button>`)}
function requests(){return page("Richieste","Ferie e licenze possono essere richieste anche molti mesi prima.",`<div class="notice">Nessuna richiesta da approvare nel collaudo.</div><div class="section"><b>Regole previste</b><ul><li>Richieste future anche a 5, 6 o 10 mesi.</li><li>Il VVF può annullare una richiesta non più necessaria.</li><li>Lo storico dell'operazione resta conservato.</li><li>Il sistema segnala i conflitti con i minimi configurati.</li></ul></div>`)}
function coffee(){return page("Caffè","QR unico, quantità modificabile prima della conferma e conteggio individuale.",`<div class="grid grid2"><div class="card tile"><div style="font-size:34px">▦</div><h3>QR unico</h3><p>Scansione rapida dal telefono. Un caffè predefinito, con possibilità di aggiungerne altri prima della conferma.</p><button class="btn btn-primary" style="margin-top:15px" onclick="alert('Scanner QR verrà collegato al modulo nativo/PWA nel collaudo')">Configura QR</button></div><div class="card tile"><div style="font-size:34px">☕</div><h3>Periodo corrente</h3><p>Conteggio individuale automatico e gestione pagamenti.</p><div class="n" style="font-size:28px">0 €</div><button class="btn btn-soft" onclick="alert('Azzeramento disponibile solo all’amministratore')">Azzera periodo</button></div></div>`)}

function dayDiff(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
const TURN_LETTERS=['A','B','C','D'];
function mod32(n,m){return ((n%m)+m)%m}
function turnCodeFromIndex(index){const i=mod32(index,32);return {letter:TURN_LETTERS[i%4],cycle:Math.floor(i/4)+1,label:`${TURN_LETTERS[i%4]}${Math.floor(i/4)+1}`}}
const TURN_CALENDAR_ANCHOR='2026-01-01';
const TURN_ANCHOR_DAY_INDEX=21; // 01/01/2026 = B6 diurno, A6 notturno
function realCycleInfo(date,team){
  const dayIndex=TURN_ANCHOR_DAY_INDEX+dayDiff(TURN_CALENDAR_ANCHOR,date);
  const dayCode=turnCodeFromIndex(dayIndex), nightCode=turnCodeFromIndex(dayIndex-1);
  let phase='Riposo',code=null;
  if(dayCode.letter===team){phase='Diurno';code=dayCode}
  else if(nightCode.letter===team){phase='Notturno';code=nightCode}
  else {const teamPos=TURN_LETTERS.indexOf(team),dayPos=TURN_LETTERS.indexOf(dayCode.letter),rel=mod32(dayPos-teamPos,4);phase=rel===2?'Smontante':'Riposo'}
  return {phase,code,dayCode,nightCode,label:code?.label||''}
}
function monthGridDays(y,m){const first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(d);while(cells.length%7)cells.push(null);return cells}
function peopleForCode(code){if(!code)return [];const selected=window.__turnSkip;return state.people.filter(p=>p.attivo!==false&&p.turno===code.letter&&Number(p.salto)===Number(code.cycle)&&(!selected||Number(p.salto)===Number(selected)))}
function turnario(){
  const saved=window.__turnView||{year:new Date().getFullYear(),month:new Date().getMonth(),team:'A'};
  window.__turnView=saved;
  const monthNames=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
  const cells=monthGridDays(saved.year,saved.month), today=new Date(), todayIso=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
  const active=state.people.filter(p=>p.attivo!==false);
  const teamPeople=active.filter(p=>p.turno===saved.team).sort((a,b)=>Number(a.salto||99)-Number(b.salto||99)||a.cognome.localeCompare(b.cognome));
  const cellHtml=cells.map(day=>{
    if(!day)return '<div class="turn-cell empty"></div>';
    const d=new Date(saved.year,saved.month,day),ds=`${saved.year}-${String(saved.month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,info=realCycleInfo(ds,saved.team);
    let service='';
    if(info.phase==='Diurno') service=`<div class="turn-shift day"><b>${info.label}</b><br>DIURNO</div>`;
    else if(info.phase==='Notturno') service=`<div class="turn-shift night"><b>${info.label}</b><br>NOTTURNO</div>`;
    else if(info.phase==='Smontante') service='<div class="turn-shift rest">SMONTANTE</div>';
    else service='<div class="turn-shift rest">RIPOSO</div>';
    const names=info.code?peopleForCode(info.code):[];
    const namesHtml=names.length?`<div class="turn-names">${names.slice(0,2).map(p=>`${esc(p.nome)} ${esc(p.cognome)}`).join('<br>')}${names.length>2?`<br><span>+${names.length-2}</span>`:''}</div>`:'';
    return `<button class="turn-cell ${ds===todayIso?'today':''}" onclick="selectTurnDate('${ds}')"><span class="turn-day-number">${day}</span>${service}${namesHtml}</button>`;
  }).join('');
  const roster=teamPeople.length?teamPeople.map(p=>`<div class="turn-person"><span><b>${esc(p.nome)} ${esc(p.cognome)}</b><small>${esc(p.ruolo||'VIGILE')} · ${esc(p.turno)}${p.salto?`${p.turno}${p.salto}`:''}</small></span><span class="badge">${p.turno}${p.salto||'—'}</span></div>`).join(''):'<div class="notice">Nessun VVF attivo assegnato al turno selezionato.</div>';
  return page('Turnario','Calendario reale A/B/C/D con sequenza perpetua e salto personale.',`
    <div class="turn-toolbar">
      <button class="btn btn-soft" onclick="turnMonth(-1)">‹</button>
      <div class="turn-month-title">${monthNames[saved.month]} ${saved.year}</div>
      <button class="btn btn-soft" onclick="turnMonth(1)">›</button>
    </div>
    <div class="turn-controls">
      <div><label class="label">Turno da visualizzare</label><select id="turn-team" class="input" onchange="setTurnTeam(this.value)">${TURN_LETTERS.map(x=>`<option ${saved.team===x?'selected':''}>${x}</option>`).join('')}</select></div>
      <div><label class="label">Salto personale</label><select class="input" onchange="setTurnSkip(this.value)"><option value="">Tutti</option>${[1,2,3,4,5,6,7,8].map(x=>`<option value="${x}" ${window.__turnSkip==x?'selected':''}>${x}</option>`).join('')}</select></div>
    </div>
    <div class="notice"><b>Sequenza ufficiale:</b> A1 → B1 → C1 → D1 → … → A8 → B8 → C8 → D8. <b>Riferimento:</b> 01/01/2026 = B6 diurno / A6 notturno.</div>
    <div class="turn-calendar-wrap"><div class="turn-weekdays">${['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=>`<div>${x}</div>`).join('')}</div><div class="turn-calendar">${cellHtml}</div></div>
    <div id="turn-date-detail"></div>
    <div class="section"><h3>Personale turno ${saved.team}</h3>${roster}</div>
  `);
}
function turnMonth(delta){const v=window.__turnView||{year:new Date().getFullYear(),month:new Date().getMonth(),team:'A'};v.month+=delta;if(v.month<0){v.month=11;v.year--}if(v.month>11){v.month=0;v.year++}window.__turnView=v;render()}
function setTurnTeam(team){window.__turnView={...(window.__turnView||{}),team};window.__turnSkip='';render()}
function setTurnSkip(skip){window.__turnSkip=skip?Number(skip):'';render()}
function selectTurnDate(ds){const v=window.__turnView||{team:'A'},info=realCycleInfo(ds,v.team),names=info.code?peopleForCode(info.code):[];const el=document.getElementById('turn-date-detail');if(!el)return;el.innerHTML=`<section class="card turn-detail"><div class="section-head"><div><div class="eyebrow">${new Date(ds+'T12:00:00').toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div><h3>${info.label?`${info.label} · ${info.phase}`:info.phase}</h3></div><button class="btn btn-soft btn-small" onclick="this.closest('.turn-detail').remove()">Chiudi</button></div>${names.length?names.map(p=>`<div class="turn-person"><span><b>${esc(p.nome)} ${esc(p.cognome)}</b><small>${esc(p.ruolo||'VIGILE')} · salto ${p.salto??'—'}</small></span><span class="badge">${esc(p.turno)}${p.salto||''}</span></div>`).join(''):'<div class="muted">Nessun VVF associato a questo servizio.</div>'}</section>`;el.scrollIntoView({behavior:'smooth',block:'nearest'})}

function selectDay(y,m,d,turno){
  const active=state.people.filter(p=>p.attivo!==false);
  const cs=active.filter(p=>p.ruolo==="CAPO_SQUADRA"&&(!p.turno||p.turno===turno));
  const au=active.filter(p=>p.ruolo==="AUTISTA"&&(!p.turno||p.turno===turno));
  const vi=active.filter(p=>p.ruolo==="VIGILE"&&(!p.turno||p.turno===turno));
  const list=(arr,empty)=>arr.length?arr.map(p=>`<div class="row"><div><b>${esc(p.nome)} ${esc(p.cognome)}</b><div class="muted">${esc(p.ruolo)} · turno ${esc(p.turno||turno)}</div></div><span class="badge">ATTIVO</span></div>`).join(""):`<div class="notice">${empty}</div>`;
  const el=document.getElementById("day-detail");
  if(el)el.innerHTML=`<section class="card" style="padding:20px;margin-top:18px">
    <div class="section-head"><div><div class="eyebrow">Giorno ${String(d).padStart(2,"0")}/${String(m+1).padStart(2,"0")}/${y}</div><h2 style="margin:4px 0">Turno ${turno}</h2></div><span class="badge">A-B-C-D</span></div>
    <div class="grid grid3">
      <div><h3>Capi Squadra (${cs.length})</h3>${list(cs,"Nessun Capo Squadra assegnato a questo turno.")}</div>
      <div><h3>Autisti (${au.length})</h3>${list(au,"Nessun Autista assegnato a questo turno.")}</div>
      <div><h3>Vigili (${vi.length})</h3>${list(vi,"Nessun Vigile assegnato a questo turno.")}</div>
    </div>
  </section>`;
}

function simple(t,d){return page(t,d,`<div class="notice">Modulo predisposto per il collegamento al database Supabase.</div>`)}
function render(){
  if(state.screen==='access'){app.innerHTML=accessScreen();return}
  if(state.screen==='pin'){app.innerHTML=pinScreen();return}
  if(state.screen==='vvfList'){app.innerHTML=vvfAccessScreen();return}
  if(state.screen==='vvfPin'){app.innerHTML=vvfPinScreen();return}
  if(state.screen==='vvf'){
    if(state.section==='home')app.innerHTML=vvfHome();
    else if(state.section==='turnario')app.innerHTML=vvfSharedTurnario();
    else if(state.section==='richieste')app.innerHTML=vvfRequestsPage();
    else if(state.section==='valida')app.innerHTML=vvfValidationPage();
    else if(state.section==='caffe')app.innerHTML=vvfCoffeePage();
    else app.innerHTML=vvfHome();
    return;
  }
  let s=state.section;app.innerHTML=s==='dashboard'?dashboard():s==='personale'?personnel():s==='parametri'?params():s==='richieste'?requests():s==='caffe'?coffee():s==='turnario'?turnario():simple('Storico e backup','Consultazione e gestione');
  if((s==='personale'||s==='turnario')&&!state.loading&&!state.peopleLoaded)loadPeople();
}
function key(k){if(k==='clear')state.pin=state.pin.slice(0,-1);else if(k==='ok'){if(state.pin.length!==4)return;if(state.setup){localStorage.setItem('tvvf_admin_pin',state.pin);state.setup=false;state.pin='';state.screen='app'}else{if(state.pin===localStorage.getItem('tvvf_admin_pin')){state.pin='';state.screen='app'}else{alert('PIN non corretto');state.pin=''}}}else if(state.pin.length<4)state.pin+=k;render()}
function go(s){state.screen='app';state.section=s;render();if((s==='personale'||s==='turnario')&&!state.loading&&!state.peopleLoaded)loadPeople()}
function adminAccess(){state.screen='pin';state.pin='';render()}
function resumeVvf(){const raw=localStorage.getItem('tvvf_me');if(!state.vvfToken||!raw)return false;try{state.me=JSON.parse(raw);state.screen='vvf';state.section='home';loadVvfPermissions();loadVvfRequests();return true}catch{return false}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
if(!resumeVvf())render();
